In [1]:
from backtesting.test import SMA
import pandas as pd
from finVADER import finvader
import matplotlib.pyplot as plt
import numpy as np

C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\backtesting\test\__init__.py:8: FutureWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  return pd.read_csv(join(dirname(__file__), filename),
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\backtesting\test\__init__.py:8: FutureWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  return pd.read_csv(join(dirname(__file__), filename),
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [2]:
from backtesting import Backtest
from backtesting import Strategy
from backtesting.lib import crossover

In [3]:
# 2 list chứa index là tín hiệu sell/buy của df data_tsla, lấy ở kq bên scapestockdata.py
final_buy = [130, 4, 135, 12, 17, 147, 22, 157, 29, 36, 42, 47, 175, 51, 188, 64, 71, 80, 213, 93, 227, 107, 111, 119]
final_sell = [0, 132, 5, 140, 16, 18, 152, 26, 30, 38, 166, 44, 49, 180, 60, 67, 196, 73, 203, 85, 220, 99, 108, 116, 122]

In [4]:
stockk = pd.read_csv('data_tsla.csv')
# Initialize the 'signal' column with 0
stockk['signal'] = 0

# Set 'signal' to 1 for the indices in 'final_buy'
stockk.loc[stockk.index.isin(final_buy), 'signal'] = 1

# Set 'signal' to 0 for the indices in 'final_sell'
stockk.loc[stockk.index.isin(final_sell), 'signal'] = -1

stockk.to_csv('data_tsla_signal.csv')
stockk

,Datetime,Open,High,Low,Close,Adj Close,Volume,signal
0,2024-01-02 09:30:00,250.080002,250.899994,244.410004,248.794006,248.794006,22581347,-1
1,2024-01-02 10:00:00,248.779999,251.250000,248.050003,249.610001,249.610001,13845933,0
2,2024-01-02 10:30:00,249.600006,249.638199,246.820007,248.919998,248.919998,10503013,0
3,2024-01-02 11:00:00,248.899994,250.259995,248.339996,250.000000,250.000000,6429840,0
4,2024-01-02 11:30:00,249.994095,251.000000,249.900101,250.475403,250.475403,6197232,1
...,...,...,...,...,...,...,...,...
229,2024-01-26 13:30:00,183.490097,183.630005,182.291000,182.644394,182.644394,5029161,0
230,2024-01-26 14:00:00,182.654999,182.660004,182.100006,182.280106,182.280106,3917711,0
231,2024-01-26 14:30:00,182.300003,183.380005,182.119995,183.270004,183.270004,4844718,0
232,2024-01-26 15:00:00,183.270004,183.320007,182.380005,182.630005,182.630005,5169574,0
233,2024-01-26 15:30:00,182.629898,183.470001,182.610001,183.229904,183.229904,7488537,0

In [5]:
class finVADERnSMA1(Strategy):
    def init(self):
        pass

    def next(self):
        signal = self.data.signal[-1]
        if signal == 1:
            self.position.close()
            self.buy()
        elif signal == -1:
            self.position.close()
            self.sell()

In [6]:
stock = pd.read_csv('data_tsla_signal.csv', index_col='Datetime', parse_dates=True)
#stock = stock.rename(columns={'Datetime': 'date'})

# Sử dụng Backtest với dữ liệu mới
bt2 = Backtest(stock, finVADERnSMA1, cash=100000, commission=.002)
stat2 = bt2.run()
bt2.plot()
stat2

C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\backtesting\_plotting.py:659: UserWarning: found multiple competing values for 'toolbar.active_drag' property; using the latest value
  fig = gridplot(
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\backtesting\_plotting.py:659: UserWarning: found multiple competing values for 'toolbar.active_scroll' property; using the latest value
  fig = gridplot(

Start                     2024-01-02 09:30:00
End                       2024-01-26 15:30:00
Duration                     24 days 06:00:00
Exposure Time [%]                   97.863248
Equity Final [$]                 102034.90073
Equity Peak [$]                 102871.084743
Return [%]                           2.034901
Buy & Hold Return [%]              -26.352766
Return (Ann.) [%]                   58.095868
Volatility (Ann.) [%]              119.772842
Sharpe Ratio                          0.48505
Sortino Ratio                        1.622214
Calmar Ratio                         3.462723
Max. Drawdown [%]                  -16.777509
Avg. Drawdown [%]                   -3.906727
Max. Drawdown Duration       23 days 01:30:00
Avg. Drawdown Duration        4 days 19:54:00
# Trades                                   48
Win Rate [%]                             37.5
Best Trade [%]                      13.406297
Worst Trade [%]                     -3.004702
Avg. Trade [%]                       0.041926
Max. Trade Duration           3 days 20:00:00
Avg. Trade Duration           0 days 12:05:00
Profit Factor                        1.116593
Expectancy [%]                       0.066456
SQN                                  0.143037
_strategy                       finVADERnSMA1
_equity_curve                             ...
_trades                       Size  EntryB...
dtype: object

In [7]:
# 2 list chứa index là tín hiệu sell/buy của df data_tsla, lấy ở kq bên scrapestockdata.py
Trade_Buy=[4, 12, 17, 22, 29, 36, 42, 47, 51, 64, 71, 80, 93, 107, 111, 119, 130, 135, 147, 157, 175, 188, 213, 227]
Trade_Sell=[0, 5, 16, 18, 26, 30, 38, 44, 49, 60, 67, 73, 85, 99, 108, 116, 122, 132, 140, 152, 166, 180, 196, 220]

In [8]:
stockk1 = pd.read_csv('data_tsla.csv')
# Initialize the 'signal' column with 0
stockk1['signal'] = 0

# Set 'signal' to 1 for the indices in 'final_buy'
stockk1.loc[stockk1.index.isin(Trade_Buy), 'signal'] = 1

# Set 'signal' to 0 for the indices in 'final_sell'
stockk1.loc[stockk1.index.isin(Trade_Sell), 'signal'] = -1

stockk1.to_csv('data_tsla_signal1.csv')
stockk1

,Datetime,Open,High,Low,Close,Adj Close,Volume,signal
0,2024-01-02 09:30:00,250.080002,250.899994,244.410004,248.794006,248.794006,22581347,-1
1,2024-01-02 10:00:00,248.779999,251.250000,248.050003,249.610001,249.610001,13845933,0
2,2024-01-02 10:30:00,249.600006,249.638199,246.820007,248.919998,248.919998,10503013,0
3,2024-01-02 11:00:00,248.899994,250.259995,248.339996,250.000000,250.000000,6429840,0
4,2024-01-02 11:30:00,249.994095,251.000000,249.900101,250.475403,250.475403,6197232,1
...,...,...,...,...,...,...,...,...
229,2024-01-26 13:30:00,183.490097,183.630005,182.291000,182.644394,182.644394,5029161,0
230,2024-01-26 14:00:00,182.654999,182.660004,182.100006,182.280106,182.280106,3917711,0
231,2024-01-26 14:30:00,182.300003,183.380005,182.119995,183.270004,183.270004,4844718,0
232,2024-01-26 15:00:00,183.270004,183.320007,182.380005,182.630005,182.630005,5169574,0
233,2024-01-26 15:30:00,182.629898,183.470001,182.610001,183.229904,183.229904,7488537,0

In [9]:
class SMA1(Strategy):
    def init(self):
        pass

    def next(self):
        signal = self.data.signal[-1]
        if signal == 1:
            self.position.close()
            self.buy()
        elif signal == -1:
            self.position.close()
            self.sell()

In [10]:
stock = pd.read_csv('data_tsla_signal1.csv', index_col='Datetime', parse_dates=True)
#stock = stock.rename(columns={'Datetime': 'date'})

# Sử dụng Backtest với dữ liệu mới
bt2 = Backtest(stock, SMA1, cash=100000, commission=.002)
stat2 = bt2.run()
bt2.plot()
stat2

C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\backtesting\_plotting.py:659: UserWarning: found multiple competing values for 'toolbar.active_drag' property; using the latest value
  fig = gridplot(
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\backtesting\_plotting.py:659: UserWarning: found multiple competing values for 'toolbar.active_scroll' property; using the latest value
  fig = gridplot(

Start                     2024-01-02 09:30:00
End                       2024-01-26 15:30:00
Duration                     24 days 06:00:00
Exposure Time [%]                   97.863248
Equity Final [$]                102158.409375
Equity Peak [$]                 102996.091988
Return [%]                           2.158409
Buy & Hold Return [%]              -26.352766
Return (Ann.) [%]                   60.796201
Volatility (Ann.) [%]              121.320904
Sharpe Ratio                         0.501119
Sortino Ratio                        1.697616
Calmar Ratio                         3.623673
Max. Drawdown [%]                  -16.777509
Avg. Drawdown [%]                   -3.907056
Max. Drawdown Duration       23 days 01:00:00
Avg. Drawdown Duration        4 days 19:48:00
# Trades                                   47
Win Rate [%]                        36.170213
Best Trade [%]                      13.711293
Worst Trade [%]                     -3.004702
Avg. Trade [%]                       0.045291
Max. Trade Duration           3 days 20:00:00
Avg. Trade Duration           0 days 12:20:00
Profit Factor                        1.122166
Expectancy [%]                       0.071114
SQN                                  0.149427
_strategy                                SMA1
_equity_curve                             ...
_trades                       Size  EntryB...
dtype: object

In [11]:
''' 
list chứa tín hiệu sell/buy của df data_tsla, tuy nhiên là df tsla_cleaned.csv có mốc thời gian sát nhau
nên nếu trong cùng một ngày/mốc thời gian có chung tín hiệu thì chỉ lấy index cuối cùng của tín hiệu đó
'''
finvader_buy=[73, 99]
finvader_sell=[203]

In [12]:
stockk2 = pd.read_csv('data_tsla.csv')
# Initialize the 'signal' column with 0
stockk2['signal'] = 0

# Set 'signal' to 1 for the indices in 'final_buy'
stockk2.loc[stockk2.index.isin(finvader_buy), 'signal'] = 1

# Set 'signal' to 0 for the indices in 'final_sell'
stockk2.loc[stockk2.index.isin(finvader_sell), 'signal'] = -1

stockk2.to_csv('data_tsla_signal2.csv')
stockk2

,Datetime,Open,High,Low,Close,Adj Close,Volume,signal
0,2024-01-02 09:30:00,250.080002,250.899994,244.410004,248.794006,248.794006,22581347,0
1,2024-01-02 10:00:00,248.779999,251.250000,248.050003,249.610001,249.610001,13845933,0
2,2024-01-02 10:30:00,249.600006,249.638199,246.820007,248.919998,248.919998,10503013,0
3,2024-01-02 11:00:00,248.899994,250.259995,248.339996,250.000000,250.000000,6429840,0
4,2024-01-02 11:30:00,249.994095,251.000000,249.900101,250.475403,250.475403,6197232,0
...,...,...,...,...,...,...,...,...
229,2024-01-26 13:30:00,183.490097,183.630005,182.291000,182.644394,182.644394,5029161,0
230,2024-01-26 14:00:00,182.654999,182.660004,182.100006,182.280106,182.280106,3917711,0
231,2024-01-26 14:30:00,182.300003,183.380005,182.119995,183.270004,183.270004,4844718,0
232,2024-01-26 15:00:00,183.270004,183.320007,182.380005,182.630005,182.630005,5169574,0
233,2024-01-26 15:30:00,182.629898,183.470001,182.610001,183.229904,183.229904,7488537,0

In [13]:
class finVADER(Strategy):
    def init(self):
        pass

    def next(self):
        signal = self.data.signal[-1]
        if signal == 1:
            self.position.close()
            self.buy()
        elif signal == -1:
            self.position.close()
            self.sell()

In [14]:
stock = pd.read_csv('data_tsla_signal2.csv', index_col='Datetime', parse_dates=True)
#stock = stock.rename(columns={'Datetime': 'date'})

# Sử dụng Backtest với dữ liệu mới
bt2 = Backtest(stock, finVADER, cash=100000, commission=.002)
stat2 = bt2.run()
bt2.plot()
stat2

C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\backtesting\_plotting.py:659: UserWarning: found multiple competing values for 'toolbar.active_drag' property; using the latest value
  fig = gridplot(
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\backtesting\_plotting.py:659: UserWarning: found multiple competing values for 'toolbar.active_scroll' property; using the latest value
  fig = gridplot(

Start                     2024-01-02 09:30:00
End                       2024-01-26 15:30:00
Duration                     24 days 06:00:00
Exposure Time [%]                   68.376068
Equity Final [$]                100076.910374
Equity Peak [$]                 100850.368091
Return [%]                            0.07691
Buy & Hold Return [%]              -26.352766
Return (Ann.) [%]                    1.082145
Volatility (Ann.) [%]               57.313076
Sharpe Ratio                         0.018881
Sortino Ratio                        0.049067
Calmar Ratio                         0.088982
Max. Drawdown [%]                  -12.161393
Avg. Drawdown [%]                    -3.87786
Max. Drawdown Duration       14 days 21:30:00
Avg. Drawdown Duration        4 days 06:30:00
# Trades                                    3
Win Rate [%]                        33.333333
Best Trade [%]                      12.592716
Worst Trade [%]                     -8.213838
Avg. Trade [%]                       0.024721
Max. Trade Duration          13 days 00:00:00
Avg. Trade Duration           5 days 16:30:00
Profit Factor                        1.106726
Expectancy [%]                       0.404788
SQN                                  0.004461
_strategy                            finVADER
_equity_curve                             ...
_trades                      Size  EntryBa...
dtype: object